### ISSUE TITLE
Index out of bound in clr_flg vector

### ISSUE THREAD

**Issue by lucaregini** [bharathp666/opencv_qr#3]
The following line of code:

if ((clr_flg[lx - 1] == blob_count) || (clr_flg[lx + 1] == blob_count))        //Check for the continuity with previous scanned data

is executed with lx=0 and lx= size_of(clr_flg)-1 causing a runtime crash.

**Comment by bharathp666** [comment]
Seems like you referencing to 'Connected Components' program. I'll get back soon.

**Comment by lucaregini** [comment]
Yes I apologize, in fact I was referring to the openar project as I found the crash while debugging and compilying on visual studio. I made a small fix to the code so that it can compile on windows. You used an extensions that should be supported by gcc only. I am moving the issue to openAR and I will raise a pull request.
