### ISSUE TITLE
ERR: Unable find input Video source.

### ISSUE THREAD

**Issue by yinshi1986** [bharathp666/opencv_qr#4]
Hi
Thanks very much for providing this code  and I am going to use it for a robotics project , try to run the code on a virtual machine which installed ubuntu 14.04 and the host is windows 8.1 ,  after finish the readme , it just tell me  ERR: Unable find input Video source.

**Comment by bharathp666** [comment]
You need to 'map' the USB Webcam to the Virtual Machine. This procedure might be helpful -
http://www.howtogeek.com/howto/31726/mount-usb-devices-in-virtualbox-with-ubuntu/
